language: node_js
node_js:
  - '8'

# Forces travis to use VM insted container, required to be able to build containers.
sudo: required

# Disable git shallow clone. We need full history for validating copyright year of each file.
git:
  depth: false

services:
  - docker

dist: trusty

env:
  global:
    # Should be encrypted or set as private travis variables (in travis settings):
    # DOCKER_HUB_EMAIL
    # DOCKER_HUB_USERNAME
    # DOCKER_HUB_PASSWORD

    # Docker repository name
    - DOCKER_REPOSITORY="mendersoftware/gui"

jobs:
  include:
    - stage: Static code checks
      script:
        # Check commit compliance.
        - git clone git://github.com/mendersoftware/mendertesting
        - mendertesting/check_commits.sh
        - npm run lint

    # - stage: Tests
    #   name: 'acceptance'
    #   install: skip
    #   script:
    #     - git clone https://github.com/mendersoftware/integration.git ;
    #     - cp -r integration/tests/* tests
    #     - GUI_REPOSITORY=$(pwd) INTEGRATION_PATH=$(pwd)/integration ./tests/e2e_tests/run

    - stage: Build and publish
      name: 'dockerhub'
      if: type = push
      install: skip
      script:
        # Build docker image from docker file
        - sudo docker build -t $DOCKER_REPOSITORY .
        # Master is always lastest
        - if [ ! -z "$TRAVIS_TAG" ]; then export IMAGE_TAG=$TRAVIS_TAG; else export IMAGE_TAG=$TRAVIS_BRANCH; fi
        - docker tag $DOCKER_REPOSITORY $DOCKER_REPOSITORY:$IMAGE_TAG
        # Upload image to docker registry only on PUSH
        - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
        - docker push $DOCKER_REPOSITORY:$IMAGE_TAG
        # tag master builds with additional commit based tag
        - if [ "$TRAVIS_BRANCH" = master ]; then
          export COMMIT_TAG="$TRAVIS_BRANCH"_"$TRAVIS_COMMIT";
          docker tag $DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REPOSITORY:$COMMIT_TAG;
          docker push $DOCKER_REPOSITORY:$COMMIT_TAG;
          fi;
