language: node_js

# Forces travis to use VM insted container, required to be able to build containers.
sudo: required

services:
    - docker

env:
    global:
        # Should be encrypted or set as private travis variables (in travis settings):
        # DOCKER_HUB_EMAIL
        # DOCKER_HUB_USERNAME
        # DOCKER_HUB_PASSWORD

        # Docker repository name
        - DOCKER_REPOSITORY="mendersoftware/gui"

before_script:
    # Set API address to docker-compose set domain. (TODO: make this configurable)
    - sed -i "s/var apiUrl.*/var apiUrl = 'http:\/\/mender-deployments:8080\/api\/0.0.1\/'/g" dist/js/main.js

script:
    # Build docker image from docker file
    - sudo docker build -t $DOCKER_REPOSITORY .

after_success:
    # Master is always lastest
    # Set latest tag only for HEAD of master branch
    # Warning: Should be executed only on git push!
    - if [ ! -z "$TRAVIS_TAG" ]; then export IMAGE_TAG=$TRAVIS_TAG; else export IMAGE_TAG=$TRAVIS_BRANCH; fi
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker tag -f $DOCKER_REPOSITORY $DOCKER_REPOSITORY:$IMAGE_TAG; fi
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD; fi
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then docker push $DOCKER_REPOSITORY:latest; fi
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push $DOCKER_REPOSITORY:$IMAGE_TAG; fi
